server:
  port: 8889

spring:
  application:
    name: config-client


#management:
#  #refresh接入点显式暴露出来
#  endpoints:
#    web:
#      exposure:
#        include: refresh,health,info  #refresh接口，可以刷新配置（POST），使得@RefreshScope标注的value可以重新注入
#
