server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/377283770/admin     # 配置git仓库的地址
          search-paths: admin                            # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: 377283770                                             # git仓库的账号（私有库必填）
          password: w1227602832c                                             # git仓库的密码（私有库必填）
      label: master                                        #配置git仓库的分支
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/

#关闭安全认证
management:
  #refresh接入点显式暴露出来
  endpoints:
    web:
      exposure:
        include: refresh,health,info,bus-refresh

