spring:
  application:
    name: eureka-server
#  profiles:
#    active: peer1

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    #表示是否将自己注册到Eureka Server，默认为true。
#    register-with-eureka: false
#    #表示是否从Eureka Server获取注册信息，默认为true。
#    fetch-registry: false
#  server:
#    # 关闭自我保护机制
#    #enable-self-preservation: false
#    # 每隔1s扫描服务列表，移除失效服务
#    eviction-interval-timer-in-ms: 1000

